### PR TITLE
feat: external documentation support

### LINKED ISSUE #61: Add support for externalDocs
Would be a nice to have to support `externalDocs` property

### PR DESCRIPTION
**Pull request by Giuliopime**
This adds support for the external documentation object.
See https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#externalDocumentationObject

Closes #61

### CODE REVIEW

**Comment by Giuliopime** [comment]
Do I have to fix wildcard imports?

**Comment by SMILEY4** [comment]
> Do I have to fix wildcard imports?

No,  i think its fine :+1: . Could you maybe disable the detekt-rule instead with this pr?  should be in "config/detekt.yml", line 786

**Comment by Giuliopime** [comment]
Done 👍🏼

**Comment by SMILEY4** [comment]
Looks good 👍 .  Thanks a lot for the pr. I will be creating+releasing a new version (2.4.0) with your changes as soon as possible.

**Pull request merged**
