### PR TITLE
support ktor.deployment.rootPath

### PR DESCRIPTION
**Pull request by mcxinyu**
Add [ktor.deployment.rootPath](https://ktor.io/docs/server-configuration-file.html#predefined-properties) to paths in openapi.json.

### CODE REVIEW

**Comment by mcxinyu** [comment]
I have no good way to get `io.ktor.server.config.ApplicationConfig` in the `io.github.smiley4.ktorswaggerui.builder.openapi.PathsBuilder` class, so I added it in the `io.github.smiley4.ktorswaggerui.routing.ControllerUtils` utils class A field for storing it, maybe you can have a good idea?

**Comment by SMILEY4** [comment]
Hi,
thanks for the pr.
Could you quickly explain why this change is necessary, i.e. which problem this is trying to solve. I think I'm overlooking something here :)

**Comment by mcxinyu** [comment]
RootPath is A [servlet](https://ktor.io/docs/server-war.html) context [path](https://ktor.io/docs/server-configuration-file.html#config-custom). 

It is the same concept as [SwaggerUIDsl.kt#L33](https://github.com/SMILEY4/ktor-swagger-ui/blob/8f579e119a2a5c5b669e1b04c719228fc7fec9b5/src/main/kotlin/io/github/smiley4/ktorswaggerui/dsl/SwaggerUIDsl.kt#L33), but ktor will add this path to the front.

It is similar to the path of a reverse proxy, but it is implemented internally within ktor.

e.g.

in route.kt
```kotlin
get("/test") {}
```

in application.conf
```
ktor {
  deployment {
    rootPath = "xxxApi"
  }
}
```

So the path of this api should be '/xxxApi/test'`.

**Comment by mcxinyu** [comment]
The problem I solved here is that the user configures `rootPath`, but the generated openapi.json did not include the path, causing 404 errors in the access interface.

**Comment by SMILEY4** [comment]
Ah, i see. Looks good then 👍
Thank you!

**Pull request merged**
